# Generated by Django 3.1.13 on 2021-11-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_edicao', models.DateTimeField(auto_now=True, verbose_name='Data de edição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70, verbose_name='Título')),
                ('foto', models.ImageField(blank=True, help_text='Tamanho sugerido (400px x 400px)', null=True, upload_to='posts/', verbose_name='Foto Home')),
                ('foto_capa', models.ImageField(blank=True, help_text='Tamanho sugerido (1200px x 300px)', null=True, upload_to='posts/', verbose_name='Foto Comunicado')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='posts/', verbose_name='Anexo')),
                ('resumo', models.TextField(null=True, verbose_name='Resumo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_edicao', models.DateTimeField(auto_now=True, verbose_name='Data de edição')),
                ('categorias', models.ManyToManyField(blank=True, to='noticias.Categoria', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-id'],
            },
        ),
    ]
