# Generated by Django 3.1.13 on 2021-11-19 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='noticias_postplugin', serialize=False, to='cms.cmsplugin')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.post')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
